// Modify kubejs/server_scripts/src/sun.js line#189, comment out ctnh:mechanical_laser input
    
    ctnh.assembly_line('ctnhcore:lasersorder')
        .itemOutputs('ctnhcore:lasersorder')
        // .itemInputs('ctnhcore:mechanical_laser')
        .itemInputs('gtceu:large_engraving_laser')
        .itemInputs('gtceu:diamond_lens')
        .itemInputs('gtceu:emerald_lens')
        .itemInputs('gtceu:ruby_lens')
        .itemInputs('gtceu:sapphire_lens')
        .itemInputs('gtceu:nether_star_lens')
        .itemInputs('gtceu:luv_emitter')
        .itemInputs('16x gtceu:optical_heat_resistant_ferrochrome_alloy_080_rod')
        .itemInputs('16x gtceu:optical_heat_resistant_ferrochrome_alloy_080_gear')
        .itemInputs('64x gtceu:long_heat_resistant_ferrochrome_alloy_ds_rod')
        .inputFluids('gtceu:cerrobase_140 1600')
        .inputFluids('gtceu:heat_resistant_ferrochrome_alloy_020 1600')
        .EUt(32678)
        .duration(800)
