// Modify kubejs/server_scripts/src/magic/Mana_Generator.js line#14, remove molten_ in line#31

    ctnh.assembly_line('ctnhcore:mana_generator_turbine_tier4')
        .itemInputs('ctnhcore:mana_generator_turbine_tier1')
        .itemInputs('ctnhcore:mana_generator_turbine_tier2')
        .itemInputs('ctnhcore:mana_generator_turbine_tier3')
        .itemInputs('gtceu:plasma_large_turbine')
        .itemInputs('64x gtceu:mana_steel_gear')
        .itemInputs('32x gtceu:elementium_gear')
        .itemInputs('16x gtceu:terra_steel_gear')
        .itemInputs('8x gtceu:alfsteel_gear')
        .itemInputs('4x gtceu:mana_plus_gear')
        .itemInputs('2x gtceu:mana_super_plus_gear')
        .itemInputs('botania:rune_fire')
        .itemInputs('botania:rune_summer')
        .itemInputs('botania:rune_wrath')
        .itemInputs('botania:rune_wrath')
        .itemInputs('ctnhcore:horizen_rune')
        .itemInputs('4x ctnhcore:alfsteel_casing')
        .inputFluids('gtceu:cerrobase_140 16000')   // remove molten_
        .inputFluids('gtceu:mana_stable_cooldown 16000')
        .itemOutputs('ctnhcore:mana_generator_turbine_tier4')
        .EUt(7680 * 4)
        .duration(400)