package io.github.tonycrane.tcpatch.mixin.ctnhcore;

import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.utils.memoization.GTMemoizer;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Pseudo;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * CTNH-Core: Demon Will Generator multiblock pattern fix.
 *
 * Don't check amount of energy output, allow using laser output.
 */
@Pseudo
@Mixin(targets = "io.github.cpearl0.ctnhcore.registry.machines.multiblock.MultiblocksA", remap = false)
public abstract class MixinMultiblocksA_DemonWillGenerator_PatternFix {

    @Shadow
    @Final
    private static MultiblockMachineDefinition DEMON_WILL_GENERATOR;

    @Unique
    private static boolean tcpatch$demonWillGenerator$patched;

    @Inject(method = "<clinit>", at = @At("TAIL"))
    private static void tcpatch$demonWillGenerator$patchPattern(CallbackInfo ci) {
        if (tcpatch$demonWillGenerator$patched) return;
        tcpatch$demonWillGenerator$patched = true;

        var definition = DEMON_WILL_GENERATOR;
        if (definition == null) return;

        definition.setPatternFactory(GTMemoizer.memoize(() -> FactoryBlockPattern.start()
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      C                   C      ", "      C                   C      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      D                   D      ", "      C                   C      ", "      E                   E      ", "    BCECB               BCECB    ", "      C                   C      ", "      D                   D      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      B                   B      ", "  B   F   B           B   F   B  ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      B                   B      ", "      G                   G      ", "  C  H H  C           C  H H  C  ", "  C       C           C       C  ", "     H H                 H H     ", "      G                   G      ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      F                   F      ", "      C                   C      ", "      I       JJJJJ       I      ", "  D  BKB  D           D  BKB  D  ", "  C  GKG  C           C  GKG  C  ", " CE B K B EC         CE B K B EC ", "BCE F K F ECB       BCE F K F ECB", "  C B K B C           C B K B C  ", "  D  GKG  D           D  GKG  D  ", "     BKB                 BKB     ", "      I                   Z      ", "      C                   C      ", "      F                   F      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "             LBLBLBL             ", "           JJJNNNNNJJJ           ", "      B       JLJLJ       B      ", "      G                   G      ", "  C  H H  C           C  H H  C  ", "  C       C           C       C  ", "     H H                 H H     ", "      G                   G      ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "          BNNN     NNNB          ", "           JLJ     JLJ           ", "                                 ", "      B                   B      ", "  B   F   B           B   F   B  ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "               BFB               ", "              E H E              ", "                                 ", "                                 ", "              FBHBF              ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "              EEEEE              ", "                                 ", "        B               B        ", "      D                   D      ", "      C       NNNNN       C      ", "     CEC                 CEC     ", "    BCECB               BCECB    ", "      C                   C      ", "      D                   D      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                H                ", "             OO   OO             ", "           FE       EF           ", "           E         E           ", "       JN               NJ       ", "        J               J        ", "             N     N             ", "      C                   C      ", "      C                   C      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                M                ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "               OOO               ", "            O       O            ", "           E         E           ", "                                 ", "       JN               NJ       ", "        L               L        ", "                                 ", "                                 ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("               MMM               ", "                                 ", "                                 ", "                                 ", "                                 ", "                M                ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "               M M               ", "               K K               ", "               G G               ", "               G G               ", "               K K               ", "               O O               ", "             O     O             ", "           O         O           ", "                                 ", "       P                 L       ", "       JN               NJ       ", "        J               J        ", "           N         N           ", "                                 ", "                K                ", "                I                ", "                F                ", "                F                ", "                I                ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("              MMMMM              ", "              M   M              ", "              M   M              ", "              M   M              ", "              MMMMM              ", "              M M M              ", "                M                ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                M                ", "               QMQ               ", "              MR RM              ", "              I   I              ", "              F   F              ", "              F   F              ", "              I   I              ", "              O S O              ", "                S                ", "           O    S    O           ", "          E     S     E          ", "       B E      S      E B       ", "      JN                 NJ      ", "       J                 J       ", "         FN           NF         ", "                                 ", "               K K               ", "               G G               ", "               G G               ", "               K K               ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("             MMMMMMM             ", "               OOO               ", "               OOO               ", "               OOO               ", "              MOOOM              ", "               MMM               ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                T                ", "                T                ", "                T                ", "                T                ", "                T                ", "                U                ", "                G                ", "                G                ", "                G                ", "                G                ", "               E E               ", "               F F               ", "              QF FQ              ", "             MR   RM             ", "             K     K             ", "             G  S  G             ", "             G  S  G             ", "             K  S  K             ", "             O SVS O             ", "            O  SVS  O            ", "               SVS               ", "         BE    SVS    EB         ", "       P       SVS       L       ", "      JN        S        NJ      ", "       L                 L       ", "         BN           NB         ", "                W                ", "              K   K              ", "              G   G              ", "              G   G              ", "              K   K              ", "               W W               ", "               X X               ", "               X X               ", "               W W               ", "                U                ", "                Y                ", "                Y                ", "                U                ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("            MMMMMMMMM            ", "               OOO               ", "               OOO               ", "               OOO               ", "              MOOOM              ", "             MMMMMMM             ", "              M F M              ", "                                 ", "                F                ", "                C                ", "                C                ", "               TUT               ", "               TUT               ", "               TUT               ", "               TUT               ", "               TUT               ", "               UUU               ", "               GFG               ", "               GFG               ", "               GFG               ", "               GFG               ", "                I                ", "              M   M              ", "              M   M              ", "                                 ", "                S                ", "               SVS               ", "               SVS               ", "               SVS               ", "              SVVVS              ", "           HO SVVVS OH           ", "              SVVVS              ", "         FE   SVVVS   EF         ", "       B H     SVS     H B       ", "      JN       SVS       NJ      ", "       J        S        J       ", "         HN     W     NH         ", "               WWW               ", "             K     K             ", "             I     I             ", "             F     F             ", "             F     F             ", "             I     I             ", "                                 ", "                                 ", "                                 ", "               UUU               ", "               YFY               ", "               YFY               ", "               UUU               ", "                U                ", "                C                ", "                C                ", "                F                ")
                .aisle("             MMMMMMM             ", "               OOO               ", "               O@O               ", "               OOO               ", "              MOOOM              ", "               MMM               ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                T                ", "                T                ", "                T                ", "                T                ", "                T                ", "                U                ", "                G                ", "                G                ", "                G                ", "                G                ", "               E E               ", "               F F               ", "              QF FQ              ", "             MR   RM             ", "             K     K             ", "             G  S  G             ", "             G  S  G             ", "             K SVS K             ", "             O SVS O             ", "            O  SVS  O            ", "               SVS               ", "         BE    SVS    EB         ", "       P        S        L       ", "      JN        S        NJ      ", "       L                 L       ", "         BN           NB         ", "                W                ", "              K   K              ", "              G   G              ", "              G   G              ", "              K   K              ", "               W W               ", "               X X               ", "               X X               ", "               W W               ", "                U                ", "                Y                ", "                Y                ", "                U                ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("              MMMMM              ", "              M   M              ", "              M   M              ", "              M   M              ", "              MMMMM              ", "              M M M              ", "                M                ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                M                ", "               QMQ               ", "              MR RM              ", "              I   I              ", "              F   F              ", "              F   F              ", "              I S I              ", "              O S O              ", "                S                ", "           O    S    O           ", "          E     S     E          ", "       B E             E B       ", "      JN                 NJ      ", "       J                 J       ", "         FN           NF         ", "                                 ", "               K K               ", "               G G               ", "               G G               ", "               K K               ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("               MMM               ", "                                 ", "                                 ", "                                 ", "                                 ", "                M                ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "               M M               ", "               K K               ", "               G G               ", "               G G               ", "               K K               ", "               O O               ", "             O     O             ", "           O         O           ", "                                 ", "       P                 L       ", "       JN               NJ       ", "        J               J        ", "           N         N           ", "                                 ", "                K                ", "                I                ", "                F                ", "                F                ", "                I                ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                M                ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "               OOO               ", "            O       O            ", "           E         E           ", "                                 ", "       JN               NJ       ", "        L               L        ", "                                 ", "                                 ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                H                ", "             OO   OO             ", "           FE       EF           ", "           E           E         ", "       JN               NJ       ", "        J               J        ", "             N     N             ", "      C                   C      ", "      C                   C      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "              EEEEE              ", "                                 ", "        B               B        ", "      D                   D      ", "      C       NNNNN       C      ", "      E                   E      ", "    BCECB               BCECB    ", "      C                   C      ", "      D                   D      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "               BFB               ", "              E H E              ", "                                 ", "                                 ", "              FBHBF              ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "          BNNN     NNNB          ", "           JLJ     JLJ           ", "                                 ", "      B                   B      ", "  B   F   B           B   F   B  ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "             LBLBLBL             ", "           JJJNNNNNJJJ           ", "      B       JLJLJ       B      ", "      G                   G      ", "  C  H H  C           C  H H  C  ", "  C       C           C       C  ", "     H H                 H H     ", "      G                   G      ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      F                   F      ", "      C                   C      ", "      I       JJJJJ       I      ", "  D  BKB  D           D  BKB  D  ", "  C  GKG  C           C  GKG  C  ", " CE B K B EC         CE B K B EC ", "BCE F K F ECB       BCE F K F ECB", "  C B K B C           C B K B C  ", "  D  GKG  D           D  GKG  D  ", "     BKB                 BKB     ", "      Z                   I      ", "      C                   C      ", "      F                   F      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      B                   B      ", "      G                   G      ", "  C  H H  C           C  H H  C  ", "  C       C           C       C  ", "     H H                 H H     ", "      G                   G      ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      B                   B      ", "  B   F   B           B   F   B  ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      D                   D      ", "      C                   C      ", "     CEC                 CEC     ", "    BCECB               BCECB    ", "      C                   C      ", "      D                   D      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      C                   C      ", "      C                   C      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .aisle("                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "      B                   B      ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ", "                                 ")
                .where("A", Predicates.blocks(Blocks.WHITE_CONCRETE))
                .where(" ", Predicates.any())
                .where("B", Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "DUNGEON_BRICK_STAIRS")))
                .where("C", Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "DUNGEON_BRICK_WALL")))
                .where("D", Predicates.blocks(Blocks.NETHER_BRICK_FENCE))
                .where("E", Predicates.blocks(Blocks.BLACK_CONCRETE))
                .where("F", Predicates.blocks(Blocks.IRON_BARS))
                .where("G", Predicates.blocks(Blocks.RED_STAINED_GLASS))
                .where("H", Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "DUNGEON_BRICK_SLAB")))
                .where("I", Predicates.blocks(com.gregtechceu.gtceu.common.data.GTBlocks.LAMPS.get(DyeColor.RED).get()))
                .where("J", Predicates.blocks(Blocks.POLISHED_BLACKSTONE_SLAB))
                .where("K", Predicates.blocks(Blocks.RED_CONCRETE))
                .where("L", Predicates.blocks(Blocks.POLISHED_BLACKSTONE_STAIRS))
                .where("M", Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "DUNGEON_BRICK_1")))
                .where("N", Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "BLANK_RUNE"))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "SPEED_RUNE")))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "SPEED_RUNE_2")))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "SACRIFICE_RUNE")))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "SACRIFICE_RUNE_2")))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "SELF_SACRIFICE_RUNE")))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "SELF_SACRIFICE_RUNE_2")))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "CAPACITY_RUNE")))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "CAPACITY_RUNE_2")))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "AUGMENTED_CAPACITY_RUNE")))
                        .or(Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "AUGMENTED_CAPACITY_RUNE_2"))))
                .where("O", Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "OBSIDIAN_TILE_PATH"))
                        .or(Predicates.autoAbilities(definition.getRecipeTypes(), true, false, true, true, true, true))
                        .or(Predicates.abilities(PartAbility.OUTPUT_ENERGY))
                        .or(Predicates.abilities(PartAbility.SUBSTATION_OUTPUT_ENERGY))
                        .or(Predicates.abilities(PartAbility.OUTPUT_LASER)))
                .where("P", Predicates.blocks(Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS))
                .where("Q", Predicates.blocks(Blocks.RED_STAINED_GLASS_PANE))
                .where("R", Predicates.blocks(Blocks.BLUE_STAINED_GLASS_PANE))
                .where("S", Predicates.blocks(tcpatch$resolveBlock("vazkii.botania.common.block.BotaniaBlocks", "bifrostPerm")))
                .where("T", Predicates.blocks(Blocks.ORANGE_STAINED_GLASS_PANE))
                .where("U", Predicates.blocks(Blocks.GRAY_CONCRETE))
                .where("V", Predicates.blocks(tcpatch$resolveAe2QuartzVibrantGlass()))
                .where("W", Predicates.blocks(Blocks.PURPLE_CONCRETE))
                .where("X", Predicates.blocks(Blocks.PURPLE_STAINED_GLASS))
                .where("Y", Predicates.blocks(Blocks.GRAY_STAINED_GLASS))
                .where("Z", Predicates.blocks(tcpatch$resolveBlock("wayoftime.bloodmagic.common.block.BloodMagicBlocks", "HELLFORGED_BLOCK")))
                .where("@", Predicates.controller(Predicates.blocks(definition.get())))
                .build()));

        // Ensure JEI/XEI previews use the updated patternFactory instead of any pre-baked shapes.
        definition.setShapes(java.util.List::of);
    }

    @Unique
    private static Block tcpatch$resolveAe2QuartzVibrantGlass() {
        // AE2: appeng.core.definitions.AEBlocks.QUARTZ_VIBRANT_GLASS.block()
        Object aeBlocks = tcpatch$getStaticField("appeng.core.definitions.AEBlocks", "QUARTZ_VIBRANT_GLASS");
        Object maybeBlock = tcpatch$invokeNoArg(aeBlocks, "block");
        if (maybeBlock instanceof Block b) return b;
        // Fallback: some versions may expose get() directly.
        maybeBlock = tcpatch$invokeNoArg(aeBlocks, "get");
        if (maybeBlock instanceof Block b) return b;
        throw new IllegalStateException("Failed to resolve AE2 QUARTZ_VIBRANT_GLASS block");
    }

    @Unique
    private static Block tcpatch$resolveBlock(String className, String fieldName) {
        Object holder = tcpatch$getStaticField(className, fieldName);
        if (holder instanceof Block b) return b;

        Object resolved = tcpatch$invokeNoArg(holder, "get");
        if (resolved instanceof Block b) return b;

        resolved = tcpatch$invokeNoArg(holder, "block");
        if (resolved instanceof Block b) return b;

        throw new IllegalStateException("Failed to resolve block from " + className + "#" + fieldName + ": " + holder);
    }

    @Unique
    private static Object tcpatch$getStaticField(String className, String fieldName) {
        try {
            Class<?> clazz = Class.forName(className);
            var field = clazz.getDeclaredField(fieldName);
            field.setAccessible(true);
            return field.get(null);
        } catch (Throwable t) {
            throw new RuntimeException("Failed to read field " + className + "#" + fieldName, t);
        }
    }

    @Unique
    private static Object tcpatch$invokeNoArg(Object target, String methodName) {
        if (target == null) return null;
        try {
            var method = target.getClass().getMethod(methodName);
            method.setAccessible(true);
            return method.invoke(target);
        } catch (NoSuchMethodException ignored) {
            return null;
        } catch (Throwable t) {
            throw new RuntimeException("Failed to invoke " + target.getClass().getName() + "#" + methodName + "()", t);
        }
    }
}
